### ISSUE TITLE
Sobre Pull Request

### ISSUE THREAD

**Issue by luan0ap** [gabrieldarezzo/helpjs-ravi#1]
Seria interessante, ser enviado um PR com os exercícios resolvidos?

**Comment by crisgon** [comment]
Concordo. Ótimo pro pessoal poder comentar sobre o código e nos ajudar a escrever códigos melhores :D

**Comment by gabrieldarezzo** [comment]
Boa, pode mandar.
Se tiver duvida em algum exercício ou não ficou claro pode abrir uma Issue ou sugerir uma PR
