### ISSUE TITLE
questão 17

### ISSUE THREAD

**Issue by badwxlf** [gabrieldarezzo/helpjs-ravi#11]
man, quando eu dou 2 ou + para função e uso if && else, eu tenho que tratar de alguma forma diferente? pq eu to trabalhando com eles da mesma forma que antes e ñ to conseguido fazer a quest. 17

**Comment by gabrieldarezzo** [comment]
Provavelmente vc já resolveu kkk (vide que é de 2020) kkkcrying :( 

Mas a soma em JavaScript tem essa pegadinha mesmo. (Ou qualquer linguagem fracamente tipada) 
Principalmente se vc está pegando os números de algum `<input type=text name="soma1">`.
Inicialmente tudo que vem da 'Web' é  sempre strings, então cabe sempre você tratar e efetuar a conversão/cast dos tipos.

Nesse caso, vc precisa garantir que oq está pegando é:
 - Um numérico.
 - Do tipo inteiro / integer ([Leitura adicional](https://www.tutorialsteacher.com/articles/how-to-get-type-of-object-in-javascript#:~:text=Use%20the%20typeof%20operator%20to,object%20or%20variable%20in%20JavaScript.&text=The%20typeof%20operator%20also%20returns,with%20the%20%22new%22%20keyword.&text=As%20you%20can%20see%20in,string%20and%20a%20string%20object.))
 
Vou atualizar e adicionar alguns exercícios antes da soma com base na sua dúvida.
