### ISSUE TITLE
Questão 8

### ISSUE THREAD

**Issue by Kauanphbbb** [gabrieldarezzo/helpjs-ravi#14]
Eu consegui fazer a máscara para o cpf, mas ela só atualiza quando ele tá completo, como posso fazer pra ele atualizar conforme for digitando?

**Comment by guilhermewebdev** [comment]
Provavelmente tem a ver com o evento que usou pra disparar sua função, você deve estar utilizando o on change, mas deveria usar o on input

**Comment by Kauanphbbb** [comment]
Esse foi o código que eu fiz:
document.querySelector("#cpf").addEventListener("keyup", () => {
    const cpf = document.querySelector("#cpf").value;
    const regex = /(\d{3})(\d{3})(\d{3})(\d{2})/g;
    const newCpf = cpf.replace(regex, "\$1.\$2.\$3\-\$4");
    document.querySelector("div").innerHTML = newCpf;
});

**Comment by guilhermewebdev** [comment]
Tente algo assim, usando o input em vez do keyup, e também capturando o valor pelo evento e não pela query
```
document.querySelector("#cpf").addEventListener("input", (event) => {
    const cpf = event.target.value;
    const regex = /(\d{3})(\d{3})(\d{3})(\d{2})/g;
    document.querySelector("div").innerHTML = cpf.replace(regex, "$1.$2.$3-$4");
});
```

**Comment by Kauanphbbb** [comment]
Mesma coisa, ele formata apenas ao digitar todos os 11 números do CPF

**Comment by guilhermewebdev** [comment]
Verdade, tem a questão do regex tbm, no seu caso ele só faz o replace quando tem os 11 dígitos [assim](https://regex101.com/r/zQpI1C/2), então vai precisar usar um regex diferente, no caso ` /(\d{3})?(\d{3})?(\d{3})?(\d{2})?/g`, [assim](https://regex101.com/r/hfUzFi/1).

**Comment by Kauanphbbb** [comment]
Eu fiz um teste com esse regex e não deu muito certo, vou procurar mais sobre regex e tentar refazer essa parte

**Comment by guilhermewebdev** [comment]
Confesso que não testei o código, mas faz isso mesmo, acredito que o problema seja o regex.

**Comment by Kauanphbbb** [comment]
Dei uma pesquisada e mudei o regex para /(\d{3})(\d{1,3})?(\d{1,3})?(\d{2})?/g
Isso faz com que os pontos apareçam desde os primeiros 3 dígitos e vai sendo preenchido conforme eu digito. Foi o melhor que consegui até agora
