### ISSUE TITLE
(5) exiba a quantidade de letras que possuem o texto inserido ao clicar no botão

### ISSUE THREAD

**Issue by yurimutti** [gabrieldarezzo/helpjs-ravi#18]
Exemplos de entrada e saida exibe Ronaldo com a quantidade de letras de 6, sendo que o correto seriam 7 letras. 

Exemplos de entrada e saida:
'Gabriel' // 7
'Daniel' // 6
---> 'Ronaldo' // 6
'Dennis Ritchie' // 14 (Espaço conta)

**Comment by gabrieldarezzo** [comment]
Não tinha reparado, boa observação.
Poderia mandar um Pulo Request?
