### ISSUE TITLE
Duvidas em relação os exercícios 4 e 5

### ISSUE THREAD

**Issue by luan0ap** [gabrieldarezzo/helpjs-ravi#2]
Só para confirmar mesmo, mas eu devo fazer um input text e quando eu clicar no mesmo devo exibi-lo? O mesmo para o exercício 5 quando eu clicar neste **input text**, devo exibir o seu tamanho?

**Comment by gabrieldarezzo** [comment]
Ficou realmente confuso o enunciado.

Basicamente a ideia seria exercitar controle do evento ```onclick``` e manipulação do atributo ```value``` do JS.


Que tal reformular assim:

No HTML Crie:
1 - Campo do tipo text para preencher o nome completo.
1 - Botão com o texto: 'Exibir Nome' e ao clicar neste botão é exibido um alert com o valor do campo nome completo, ex:
'O Nome Completo é: ***xxxx***'

Exemplo de solução inline:
```html
<p>Nome Completo:</p>
<input type="text" name="nome-completo" id="nome-completo" value="Digite seu nome"/>
<br />
<input type="button" value="Exibir Nome" 
  onclick="alert('O Nome Completo é: ' + document.getElementById('nome-completo').value);" />
<hr />
```  

Ou usando o elemento 'button' msm:	
```html
<p>Nome Completo:</p>
<input type="text" name="nome-completo" id="nome-completo-btn" value="Digite seu nome (2)"/>
<br />
  <button 
    onclick="alert('O Nome Completo é: ' + document.getElementById('nome-completo-btn').value);" >
    Exibir Nome
  </button>
<hr />
``` 

Exemplo no Fiddle rodando:
https://fiddle.jshell.net/27bh7x59/

**Comment by luan0ap** [comment]
Entendi, valeu man.

**Comment by gabrieldarezzo** [comment]
https://github.com/gabrieldarezzo/helpjs-ravi/commit/269f86e119e5b5335d4a709e2a2cc6a93b514ddd
