### ISSUE TITLE
Sobre o exercício 9

### ISSUE THREAD

**Issue by luan0ap** [gabrieldarezzo/helpjs-ravi#3]
> (9) no campo texto do exercício anterior, preencha um CPF (sem pontuação e exiba o mesmo sem pontuação)

Eu devo exibir o valor do input novamente? Ou seria: "Sem pontuação e exiba o mesmo com pontuação"? Porém se for assim dai já não entra regex? O que sairia um pouco do básico, pois estava esperando ir ficando mais complexo gradualmente.

**Comment by gabrieldarezzo** [comment]
Não necessariamente.

Você pode simplesmente 'concatenar' partes da string usando o [.substring()](https://www.w3schools.com/jsref/jsref_substring.asp) 

um CPF com pontuação tem a seguinte estrutura :
{3 NUMEROS} . {3 NUMEROS} . {3 NUMEROS} - {2 NUMEROS}




A lógica se aplica ao inverso (Pontuação -> Sem pontuação)
Tem diversas funções simples para simplesmente 'remover' caracteres específicos.


Regex de qualquer forma é um mundo de possibilidades.

Vou anexar um vídeo q eu lembro que achei bem legal:
https://www.youtube.com/watch?v=mxdBtYKlKJw

**Comment by gabrieldarezzo** [comment]
Mas a critica foi boa, talvez aplicar exercicios de concatenação e uso de substring antes desse do CPF,

Vlw pela dica 👍
