### ISSUE TITLE
Questão 12

### ISSUE THREAD

**Issue by marcostomaz2013** [gabrieldarezzo/helpjs-ravi#5]
Ei amigo, como assim comentário, você está dizendo somente comentar tipo exemplo:

<script type=text/javascript>
//Está váriavel num, tem o valor 15!
var num = 15;
</script>

**Comment by gabrieldarezzo** [comment]
Sim, a ideia do exercício, é exatamente esta.

Adicionar um comentário de uma linha:
```html
<script type="text/javascript">
	// Isto é um comentário de uma linha 
	var abc = 3;	
</script>
``` 


```html
<script type="text/javascript">
	/*
	Isto é um comentário de 
	varias 
	linha 
	*/
	var abc = 3;	
</script>
```
