### ISSUE TITLE
Questão 14

### ISSUE THREAD

**Issue by yaggolc** [gabrieldarezzo/helpjs-ravi#6]
Eu não consigo ter ideia do que tá sendo pedido na 14. Falta uma definição melhor de que tipo de habilidade você tá pedindo lá. E não "traduz" as coisas. Se é alguma coisa "load" deixa load mesmo porque só vai confundir mais.

**Comment by gabrieldarezzo** [comment]
Legal o apontamento, realmente ficou confuso.

Fiz a alteração:
https://github.com/gabrieldarezzo/helpjs-ravi/commit/495ac19089063f3571122eb424f081032a3615e1

Oq achou?
