### ISSUE TITLE
Sobre o exercício 10

### ISSUE THREAD

**Issue by andrecodato** [gabrieldarezzo/helpjs-ravi#7]
>(10) No HTML Crie:
>2 x - Campo/Input do tipo text. **(id=soma1, id=soma1)**
>1 x - Botão (id=btn-soma)
>1 x - Campo (id=resultado-soma)
>Caso esteja preenchido um valor númerico nos dois **campos(id=soma1, id=soma1)**, 
>A soma deles ira aparecer no campo (id=resultado-soma) ao clicar no botão (id=btn-soma).

Isto está certo? Ambos tem id="soma1"?

**Comment by gabrieldarezzo** [comment]
Obrigado pelo apontamento. Corrigido
